#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
 * This file is part of the TYPO3 project.
 *
 * (c) 2019-2021 Benni Mack
 *               Simon Gilli
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

$setup = static function ($scriptPath, string $type = null, $forceOption = null) {
    if (($rootPath = getcwd()) === false) {
        throw new RuntimeException("Error while determining the current directory.", 1636451407);
    }

    $dir = __DIR__ . '/vendor';
    while (!file_exists($dir . '/autoload.php')) {
        if ($dir === $rootPath) {
            exit(1);
        }
        $dir = \dirname($dir);
    }
    require $dir . '/autoload.php';

    $obj = new \TYPO3\CodingStandards\Setup($rootPath);
    switch ($type) {
        case 'extension':
            return $obj->forExtension($forceOption === '-f');
        case 'project':
            return $obj->forProject($forceOption === '-f');
        default:
            echo "You need to specify at least one option. Use 'extension' or 'project'.\n";
            exit(1);
    }
};
$setup(...$_SERVER['argv']);
