name: 🐞 Bug report
description: Create a report to help us improve.
labels: [bug]
assignees:
  - gilbertsoft
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: 'Example: Ubuntu 20.04'
    validations:
      required: true
  - type: input
    id: composer
    attributes:
      label: Composer version
      description: What Composer version are you using?
      placeholder: 'Example: 2.2.4'
    validations:
      required: true
  - type: input
    id: php
    attributes:
      label: PHP version
      description: What PHP version are you using?
      placeholder: 'Example: 8.1.1'
    validations:
      required: true
  - type: dropdown
    id: release
    attributes:
      label: TYPO3 Coding Standards Package version
      description: What version of our software are you running?
      multiple: false
      options:
        - Latest stable release
        - Latest pre-release
        - Main branch
        - Other (please describe below)
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Additional version information
      description: Please provide more information about the used version if you selected `Other` above.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
