blank_issues_enabled: false
contact_links:
  - name: 🚑 Community support
    url: https://typo3.slack.com/archives/C025BQLFA
    about: Please ask and answer questions here. Register or connect your account at https://my.typo3.org/.
